// Auto-generated file, DO NOT MODIFY
using Infrastructure.Base;
using System.Windows;
using System.Windows.Media;
using System.Windows.Controls;

namespace BasicControls.Topics.AutoGeneratedTopics
{
    public partial class TextBoxProperties : PropertyChangedBase
    {
        private string _text;
        public string Text
        {
            get => _text;
            set => SetField(ref _text, value);
        }

        private bool _isReadOnly;
        public bool IsReadOnly
        {
            get => _isReadOnly;
            set => SetField(ref _isReadOnly, value);
        }

        private bool _isEnabled;
        public bool IsEnabled
        {
            get => _isEnabled;
            set => SetField(ref _isEnabled, value);
        }

        private bool _acceptsReturn;
        public bool AcceptsReturn
        {
            get => _acceptsReturn;
            set => SetField(ref _acceptsReturn, value);
        }

        private bool _acceptsTab;
        public bool AcceptsTab
        {
            get => _acceptsTab;
            set => SetField(ref _acceptsTab, value);
        }

        private int _caretIndex;
        public int CaretIndex
        {
            get => _caretIndex;
            set => SetField(ref _caretIndex, value);
        }

        private int _maxLength;
        public int MaxLength
        {
            get => _maxLength;
            set => SetField(ref _maxLength, value);
        }

        private TextAlignment _textAlignment;
        public TextAlignment TextAlignment
        {
            get => _textAlignment;
            set => SetField(ref _textAlignment, value);
        }

        private TextWrapping _textWrapping;
        public TextWrapping TextWrapping
        {
            get => _textWrapping;
            set => SetField(ref _textWrapping, value);
        }

        private ScrollBarVisibility _horizontalScrollBarVisibility;
        public ScrollBarVisibility HorizontalScrollBarVisibility
        {
            get => _horizontalScrollBarVisibility;
            set => SetField(ref _horizontalScrollBarVisibility, value);
        }

        private ScrollBarVisibility _verticalScrollBarVisibility;
        public ScrollBarVisibility VerticalScrollBarVisibility
        {
            get => _verticalScrollBarVisibility;
            set => SetField(ref _verticalScrollBarVisibility, value);
        }

        private int _selectionStart;
        public int SelectionStart
        {
            get => _selectionStart;
            set => SetField(ref _selectionStart, value);
        }

        private int _selectionLength;
        public int SelectionLength
        {
            get => _selectionLength;
            set => SetField(ref _selectionLength, value);
        }

        private string _selectedText;
        public string SelectedText
        {
            get => _selectedText;
            set => SetField(ref _selectedText, value);
        }

        private Brush _background;
        public Brush Background
        {
            get => _background;
            set => SetField(ref _background, value);
        }

        private Brush _foreground;
        public Brush Foreground
        {
            get => _foreground;
            set => SetField(ref _foreground, value);
        }

        private Brush _borderBrush;
        public Brush BorderBrush
        {
            get => _borderBrush;
            set => SetField(ref _borderBrush, value);
        }

        private Thickness _borderThickness;
        public Thickness BorderThickness
        {
            get => _borderThickness;
            set => SetField(ref _borderThickness, value);
        }

        private FontFamily _fontFamily;
        public FontFamily FontFamily
        {
            get => _fontFamily;
            set => SetField(ref _fontFamily, value);
        }

        private double _fontSize;
        public double FontSize
        {
            get => _fontSize;
            set => SetField(ref _fontSize, value);
        }

        private FontWeight _fontWeight;
        public FontWeight FontWeight
        {
            get => _fontWeight;
            set => SetField(ref _fontWeight, value);
        }

        private FontStyle _fontStyle;
        public FontStyle FontStyle
        {
            get => _fontStyle;
            set => SetField(ref _fontStyle, value);
        }

        private FontStretch _fontStretch;
        public FontStretch FontStretch
        {
            get => _fontStretch;
            set => SetField(ref _fontStretch, value);
        }

        private Thickness _padding;
        public Thickness Padding
        {
            get => _padding;
            set => SetField(ref _padding, value);
        }

        private Thickness _margin;
        public Thickness Margin
        {
            get => _margin;
            set => SetField(ref _margin, value);
        }

        private HorizontalAlignment _horizontalAlignment;
        public HorizontalAlignment HorizontalAlignment
        {
            get => _horizontalAlignment;
            set => SetField(ref _horizontalAlignment, value);
        }

        private VerticalAlignment _verticalAlignment;
        public VerticalAlignment VerticalAlignment
        {
            get => _verticalAlignment;
            set => SetField(ref _verticalAlignment, value);
        }

        private double _width;
        public double Width
        {
            get => _width;
            set => SetField(ref _width, value);
        }

        private double _height;
        public double Height
        {
            get => _height;
            set => SetField(ref _height, value);
        }

        private double _minWidth;
        public double MinWidth
        {
            get => _minWidth;
            set => SetField(ref _minWidth, value);
        }

        private double _minHeight;
        public double MinHeight
        {
            get => _minHeight;
            set => SetField(ref _minHeight, value);
        }

        private double _maxWidth;
        public double MaxWidth
        {
            get => _maxWidth;
            set => SetField(ref _maxWidth, value);
        }

        private double _maxHeight;
        public double MaxHeight
        {
            get => _maxHeight;
            set => SetField(ref _maxHeight, value);
        }

        private Visibility _visibility;
        public Visibility Visibility
        {
            get => _visibility;
            set => SetField(ref _visibility, value);
        }

        private object _toolTip;
        public object ToolTip
        {
            get => _toolTip;
            set => SetField(ref _toolTip, value);
        }

        private Style _style;
        public Style Style
        {
            get => _style;
            set => SetField(ref _style, value);
        }

        private double _opacity;
        public double Opacity
        {
            get => _opacity;
            set => SetField(ref _opacity, value);
        }

        private bool _focusable;
        public bool Focusable
        {
            get => _focusable;
            set => SetField(ref _focusable, value);
        }

        private string _name;
        public string Name
        {
            get => _name;
            set => SetField(ref _name, value);
        }

        private object _tag;
        public object Tag
        {
            get => _tag;
            set => SetField(ref _tag, value);
        }

    }
}
