using System.Windows.Controls;

namespace BasicControls.PhaseTwo.Topics.AutoGeneratedTopics.TextBox
{
    /// <summary>
    /// Interaction logic for TextBoxIntroductionView.xaml
    /// </summary>
    public partial class TextBoxIntroductionView : UserControl
    {
        public TextBoxIntroductionView()
        {
            InitializeComponent();
        }
    }
}
