using BasicControls.Common;
using Feature.Infrastructure.Core;
using Feature.Infrastructure.Interfaces;
using System.Collections.ObjectModel;
using System.ComponentModel.Composition;

namespace BasicControls.PhaseTwo.Topics.AutoGeneratedTopics.TextBox
{
    [Export(typeof(IIntroductionViewModel))]
    [ExportMetadata(MetaDataKeys.Title, AddonMetadataKeys.TextBoxTitle)]
    internal class TextBoxIntroductionViewModel : ControlIntroductionViewModel, IIntroductionViewModel
    {
        public override string Title => AddonMetadataKeys.TextBoxTitle;

        public override string Header => "TextBox Control";

        public override ObservableCollection<string> DescriptionCollection { get; } = new ObservableCollection<string>
        {
            "The TextBox control is used for single-line or multi-line text input.",
"Supports text formatting, selection, and clipboard operations.",
"Properties like IsReadOnly, MaxLength, and TextWrapping provide customization."
        };

        public override string SamplesIntroductionHeader => "Few Samples of TextBox are provided below";

        public TextBoxSampleViewModel SampleContent {get;} = new TextBoxSampleViewModel();
    }
}
