using System.Windows.Controls;

namespace PanelControls.Topics.AutoGeneratedTopics.StackPanel
{
    /// <summary>
    /// Interaction logic for StackPanelIntroductionView.xaml
    /// </summary>
    public partial class StackPanelIntroductionView : UserControl
    {
        public StackPanelIntroductionView()
        {
            InitializeComponent();
        }
    }
}
