using System.Windows.Controls;

namespace BasicControls.Topics.AutoGeneratedTopics.RadioButton
{
    /// <summary>
    /// Interaction logic for RadioButtonIntroductionView.xaml
    /// </summary>
    public partial class RadioButtonIntroductionView : UserControl
    {
        public RadioButtonIntroductionView()
        {
            InitializeComponent();
        }
    }
}
