using BasicControls.Common;
using Feature.Infrastructure.Core;
using Feature.Infrastructure.Interfaces;
using System.Collections.ObjectModel;
using System.ComponentModel.Composition;

namespace BasicControls.PhaseTwo.Topics.AutoGeneratedTopics.Image
{
    [Export(typeof(IIntroductionViewModel))]
    [ExportMetadata(MetaDataKeys.Title, AddonMetadataKeys.ImageTitle)]
    internal class ImageIntroductionViewModel : ControlIntroductionViewModel, IIntroductionViewModel
    {
        public override string Title => AddonMetadataKeys.ImageTitle;

        public override string Header => "Image Control";

        public override ObservableCollection<string> DescriptionCollection { get; } = new ObservableCollection<string>
        {
            "The Image control is used to display bitmap, PNG, JPEG, and other image formats.",
"Supports stretching, alignment, and opacity settings.",
"Can be used to enhance UI with icons, backgrounds, or decorative images."
        };

        public override string SamplesIntroductionHeader => "Few Samples of Image are provided below";

        public ImageSampleViewModel SampleContent {get;} = new ImageSampleViewModel();
    }
}
