using System.Windows.Controls;

namespace BasicControls.PhaseTwo.Topics.AutoGeneratedTopics.Image
{
    /// <summary>
    /// Interaction logic for ImageIntroductionView.xaml
    /// </summary>
    public partial class ImageIntroductionView : UserControl
    {
        public ImageIntroductionView()
        {
            InitializeComponent();
        }
    }
}
