using Infrastructure.Base;

namespace BasicControls.PhaseTwo.Topics.AutoGeneratedTopics.Image
{
    internal class ImageSampleViewModel : PropertyChangedBase
    {
        private string _dynamicImagePath;
        public string DynamicImagePath
        {
            get => _dynamicImagePath;
            set => SetField(ref _dynamicImagePath, value); // Use your PropertyChangedBase helper
        }

        public ImageSampleViewModel()
        {
            // Initialize with a default image path
            DynamicImagePath = "pack://application:,,,/BasicControls.PhaseTwo;component/Images/check_icon_green.png"; // Update with your actual image path
        }
    }
}
