using BasicControls.Common;
using Feature.Infrastructure.Core;
using Feature.Infrastructure.Interfaces;
using System.Collections.ObjectModel;
using System.ComponentModel.Composition;

namespace BasicControls.Topics.AutoGeneratedTopics.Canvas
{
    [Export(typeof(IIntroductionViewModel))]
    [ExportMetadata(MetaDataKeys.Title, AddonMetadataKeys.CanvasTitle)]
    internal class CanvasIntroductionViewModel : ControlIntroductionViewModel, IIntroductionViewModel
    {
        public override string Title => AddonMetadataKeys.CanvasTitle;

        public override string Header => "Canvas Panel";

        public override ObservableCollection<string> DescriptionCollection { get; } = new ObservableCollection<string>
        {
            "The Canvas panel allows you to position child elements using coordinates.",
"Ideal for drawing applications or scenarios requiring precise placement.",
"Children are placed using Canvas.Left and Canvas.Top attached properties."
        };

        public override string SamplesIntroductionHeader => "Few Samples of Canvas are provided below";
    }
}
