using BasicControls.Common;
using Feature.Infrastructure.Core;
using Feature.Infrastructure.Interfaces;
using System.Collections.ObjectModel;
using System.ComponentModel.Composition;

namespace BasicControls.Topics.AutoGeneratedTopics.StackPanel
{
    [Export(typeof(IIntroductionViewModel))]
    [ExportMetadata(MetaDataKeys.Title, AddonMetadataKeys.StackPanelTitle)]
    internal class StackPanelIntroductionViewModel : ControlIntroductionViewModel, IIntroductionViewModel
    {
        public override string Title => AddonMetadataKeys.StackPanelTitle;

        public override string Header => "StackPanel";

        public override ObservableCollection<string> DescriptionCollection { get; } = new ObservableCollection<string>
        {
            "The StackPanel stacks child elements in a single direction (horizontal or vertical).",
"Simple and efficient for linear layouts.",
"Does not wrap content; use WrapPanel for wrapping behavior."
        };

        public override string SamplesIntroductionHeader => "Few Samples of StackPanel are provided below";
    }
}
