using Feature.Infrastructure.AbstractImplementation;
using Feature.Infrastructure.Interfaces;
using System.ComponentModel.Composition;

namespace BasicControls.Topics.AutoGeneratedTopics
{
    [Export(typeof(IFeatureDemoTopic))]
    public class PanelControl : FeatureDemoTopic
    {
        public override string Title => AddonMetadataKeys.PanelsTitle;
    }
}
