using System.Windows.Controls;

namespace BasicControls.PhaseTwo.Topics.AutoGeneratedTopics.CheckBox
{
    /// <summary>
    /// Interaction logic for CheckBoxIntroductionView.xaml
    /// </summary>
    public partial class CheckBoxIntroductionView : UserControl
    {
        public CheckBoxIntroductionView()
        {
            InitializeComponent();
        }
    }
}
