using Infrastructure.Base;

namespace BasicControls.PhaseTwo.Topics.AutoGeneratedTopics.CheckBox
{
    internal class CheckBoxSampleViewModel : PropertyChangedBase
    {
        private bool? someNullableBool;

        public bool? SomeNullableBool
        {
            get => someNullableBool; 
            set => SetField(ref someNullableBool, value);
        }

    }
}
