using BasicControls.Common;
using Feature.Infrastructure.Core;
using Feature.Infrastructure.Interfaces;
using System.Collections.ObjectModel;
using System.ComponentModel.Composition;

namespace BasicControls.Topics.AutoGeneratedTopics.DockPanel
{
    [Export(typeof(IIntroductionViewModel))]
    [ExportMetadata(MetaDataKeys.Title, AddonMetadataKeys.DockPanelTitle)]
    internal class DockPanelIntroductionViewModel : ControlIntroductionViewModel, IIntroductionViewModel
    {
        public override string Title => AddonMetadataKeys.DockPanelTitle;

        public override string Header => "DockPanel";

        public override ObservableCollection<string> DescriptionCollection { get; } = new ObservableCollection<string>
        {
            "The DockPanel docks child elements to the top, bottom, left, or right edges.",
"The last child can fill the remaining space if LastChildFill is true.",
"Useful for toolbars, status bars, and flexible layouts."
        };

        public override string SamplesIntroductionHeader => "Few Samples of DockPanel are provided below";
    }
}
