using System.Windows.Controls;

namespace BasicControls.Topics.AutoGeneratedTopics.DockPanel
{
    /// <summary>
    /// Interaction logic for DockPanelIntroductionView.xaml
    /// </summary>
    public partial class DockPanelIntroductionView : UserControl
    {
        public DockPanelIntroductionView()
        {
            InitializeComponent();
        }
    }
}
