// Auto-generated file, DO NOT MODIFY
using Infrastructure.Base;
using System.Windows;
using System.Windows.Media;
using System.Windows.Controls;

namespace BasicControls.Topics.AutoGeneratedTopics
{
    public partial class DockPanelProperties : PropertyChangedBase
    {
        private bool _lastChildFill;
        public bool LastChildFill
        {
            get => _lastChildFill;
            set => SetField(ref _lastChildFill, value);
        }

        private double _width;
        public double Width
        {
            get => _width;
            set => SetField(ref _width, value);
        }

        private double _height;
        public double Height
        {
            get => _height;
            set => SetField(ref _height, value);
        }

        private double _minWidth;
        public double MinWidth
        {
            get => _minWidth;
            set => SetField(ref _minWidth, value);
        }

        private double _minHeight;
        public double MinHeight
        {
            get => _minHeight;
            set => SetField(ref _minHeight, value);
        }

        private double _maxWidth;
        public double MaxWidth
        {
            get => _maxWidth;
            set => SetField(ref _maxWidth, value);
        }

        private double _maxHeight;
        public double MaxHeight
        {
            get => _maxHeight;
            set => SetField(ref _maxHeight, value);
        }

        private Thickness _margin;
        public Thickness Margin
        {
            get => _margin;
            set => SetField(ref _margin, value);
        }

        private HorizontalAlignment _horizontalAlignment;
        public HorizontalAlignment HorizontalAlignment
        {
            get => _horizontalAlignment;
            set => SetField(ref _horizontalAlignment, value);
        }

        private VerticalAlignment _verticalAlignment;
        public VerticalAlignment VerticalAlignment
        {
            get => _verticalAlignment;
            set => SetField(ref _verticalAlignment, value);
        }

        private Brush _background;
        public Brush Background
        {
            get => _background;
            set => SetField(ref _background, value);
        }

        private double _opacity;
        public double Opacity
        {
            get => _opacity;
            set => SetField(ref _opacity, value);
        }

        private Visibility _visibility;
        public Visibility Visibility
        {
            get => _visibility;
            set => SetField(ref _visibility, value);
        }

        private object _toolTip;
        public object ToolTip
        {
            get => _toolTip;
            set => SetField(ref _toolTip, value);
        }

        private Style _style;
        public Style Style
        {
            get => _style;
            set => SetField(ref _style, value);
        }

        private bool _focusable;
        public bool Focusable
        {
            get => _focusable;
            set => SetField(ref _focusable, value);
        }

        private string _name;
        public string Name
        {
            get => _name;
            set => SetField(ref _name, value);
        }

        private object _tag;
        public object Tag
        {
            get => _tag;
            set => SetField(ref _tag, value);
        }

    }
}
