// Auto-generated file, DO NOT MODIFY
namespace PanelControls.Topics.AutoGeneratedTopics
{
    public partial class AddonMetadataKeys
    {
        #region Panels

        public const string PanelsTitle = "Panels";

        public const string CanvasTitle = "Canvas";
        public const string WrapPanelTitle = "Wrap Panel";
        public const string StackPanelTitle = "Stack Panel";
        public const string DockPanelTitle = "Dock Panel";
        public const string GridTitle = "Grid";

        #endregion Panels

    }
}
