// Auto-generated file, DO NOT MODIFY
using Feature.Infrastructure.Core;
using Feature.Infrastructure.Interfaces;
using System.ComponentModel.Composition;

namespace BasicControls.Topics.AutoGeneratedTopics
{
    [Export(typeof(IFeatureDemoSubTopic))]
    [ExportMetadata(MetaDataKeys.TopicName, AddonMetadataKeys.BasicControlsTitle)]
    public partial class ButtonSubTopic : IFeatureDemoSubTopic
    {
        public string Title => AddonMetadataKeys.ButtonTitle;
    }
}
