using System.Windows.Controls;

namespace BasicControls.Topics.AutoGeneratedTopics.Button
{
    /// <summary>
    /// Interaction logic for ButtonIntroductionView.xaml
    /// </summary>
    public partial class ButtonIntroductionView : UserControl
    {
        public ButtonIntroductionView()
        {
            InitializeComponent();
        }

        private void Button_Click(object sender, System.Windows.RoutedEventArgs e)
        {
            // show a message box when the button is clicked, also show the button's content
            System.Windows.MessageBox.Show("Button clicked! Content: " + (sender as System.Windows.Controls.Button).Content);
        }
    }
}
