using BasicControls.Common;
using Feature.Infrastructure.Core;
using Feature.Infrastructure.Interfaces;
using System.Collections.ObjectModel;
using System.ComponentModel.Composition;

namespace BasicControls.PhaseTwo.Topics.AutoGeneratedTopics.PasswordBox
{
    [Export(typeof(IIntroductionViewModel))]
    [ExportMetadata(MetaDataKeys.Title, AddonMetadataKeys.PasswordBoxTitle)]
    internal class PasswordBoxIntroductionViewModel : ControlIntroductionViewModel, IIntroductionViewModel
    {
        public override string Title => AddonMetadataKeys.PasswordBoxTitle;

        public override string Header => "PasswordBox Control";

        public override ObservableCollection<string> DescriptionCollection { get; } = new ObservableCollection<string>
        {
            "The PasswordBox control masks user input for sensitive data such as passwords.",
"Does not support data binding for the Password property for security reasons.",
"Supports properties like MaxLength and IsReadOnly."
        };

        public override string SamplesIntroductionHeader => "Few Samples of PasswordBox are provided below";
    }
}
