using System.Windows.Controls;

namespace BasicControls.PhaseTwo.Topics.AutoGeneratedTopics.PasswordBox
{
    /// <summary>
    /// Interaction logic for PasswordBoxIntroductionView.xaml
    /// </summary>
    public partial class PasswordBoxIntroductionView : UserControl
    {
        public PasswordBoxIntroductionView()
        {
            InitializeComponent();
        }
    }
}
