using System.ComponentModel.Composition;
using System.Windows;

namespace BasicControls.Topics.AutoGeneratedTopics.Resources
{
    [Export(typeof(ResourceDictionary))]
    [ExportMetadata("DictionaryName", "DataTemplates")]
    public class DataTemplatesResourceDictionary : ResourceDictionary
    {
        public DataTemplatesResourceDictionary()
        {
            Source = new System.Uri("/BasicControls;component/Topics/AutoGeneratedTopics/Resources/DataTemplates.xaml", System.UriKind.RelativeOrAbsolute);
        }
    }
}