// Auto-generated file, DO NOT MODIFY
namespace BasicControls.PhaseTwo.Topics.AutoGeneratedTopics
{
    public partial class AddonMetadataKeys
    {
        #region BasicControls

        public const string BasicControlsTitle = "Basic Controls";
        public const string ButtonTitle = "Button";
        public const string TextBoxTitle = "Text Box";
        public const string CheckBoxTitle = "Check Box";
        public const string RadioButtonTitle = "Radio Button";
        public const string PasswordBoxTitle = "Password Box";
        public const string ImageTitle = "Image";

        #endregion BasicControls
    }
}
