using BasicControls.Common;
using Feature.Infrastructure.Core;
using Feature.Infrastructure.Interfaces;
using System.Collections.ObjectModel;
using System.ComponentModel.Composition;

namespace BasicControls.Topics.AutoGeneratedTopics.CheckBox
{
    [Export(typeof(IIntroductionViewModel))]
    [ExportMetadata(MetaDataKeys.Title, AddonMetadataKeys.CheckBoxTitle)]
    internal class CheckBoxIntroductionViewModel : ControlIntroductionViewModel, IIntroductionViewModel
    {
        public override string Title => AddonMetadataKeys.CheckBoxTitle;

        public override string Header => "CheckBox Control";

        public override ObservableCollection<string> DescriptionCollection { get; } = new ObservableCollection<string>
        {
            "The CheckBox control represents a boolean option that can be checked, unchecked, or indeterminate.",
"Supports three-state mode for indeterminate values.",
"Can be used individually or in groups for multiple selections."
        };

        public override string SamplesIntroductionHeader => "Few Samples of CheckBox are provided below";
    }
}
