// Auto-generated file, DO NOT MODIFY
using Infrastructure.Base;
using System.Windows;
using System.Windows.Media;
using System.Windows.Controls;

namespace BasicControls.PhaseTwo.Topics.AutoGeneratedTopics
{
    public partial class RadioButtonProperties : PropertyChangedBase
    {
        private bool? _isChecked;
        public bool? IsChecked
        {
            get => _isChecked;
            set => SetField(ref _isChecked, value);
        }

        private bool _isThreeState;
        public bool IsThreeState
        {
            get => _isThreeState;
            set => SetField(ref _isThreeState, value);
        }

        private string _groupName;
        public string GroupName
        {
            get => _groupName;
            set => SetField(ref _groupName, value);
        }

        private object _content;
        public object Content
        {
            get => _content;
            set => SetField(ref _content, value);
        }

        private bool _isEnabled;
        public bool IsEnabled
        {
            get => _isEnabled;
            set => SetField(ref _isEnabled, value);
        }

        private bool _isHitTestVisible;
        public bool IsHitTestVisible
        {
            get => _isHitTestVisible;
            set => SetField(ref _isHitTestVisible, value);
        }

        private bool _isTabStop;
        public bool IsTabStop
        {
            get => _isTabStop;
            set => SetField(ref _isTabStop, value);
        }

        private int _tabIndex;
        public int TabIndex
        {
            get => _tabIndex;
            set => SetField(ref _tabIndex, value);
        }

        private object _commandParameter;
        public object CommandParameter
        {
            get => _commandParameter;
            set => SetField(ref _commandParameter, value);
        }

        private IInputElement _commandTarget;
        public IInputElement CommandTarget
        {
            get => _commandTarget;
            set => SetField(ref _commandTarget, value);
        }

        private Brush _background;
        public Brush Background
        {
            get => _background;
            set => SetField(ref _background, value);
        }

        private Brush _foreground;
        public Brush Foreground
        {
            get => _foreground;
            set => SetField(ref _foreground, value);
        }

        private Brush _borderBrush;
        public Brush BorderBrush
        {
            get => _borderBrush;
            set => SetField(ref _borderBrush, value);
        }

        private Thickness _borderThickness;
        public Thickness BorderThickness
        {
            get => _borderThickness;
            set => SetField(ref _borderThickness, value);
        }

        private FontFamily _fontFamily;
        public FontFamily FontFamily
        {
            get => _fontFamily;
            set => SetField(ref _fontFamily, value);
        }

        private double _fontSize;
        public double FontSize
        {
            get => _fontSize;
            set => SetField(ref _fontSize, value);
        }

        private FontWeight _fontWeight;
        public FontWeight FontWeight
        {
            get => _fontWeight;
            set => SetField(ref _fontWeight, value);
        }

        private FontStyle _fontStyle;
        public FontStyle FontStyle
        {
            get => _fontStyle;
            set => SetField(ref _fontStyle, value);
        }

        private FontStretch _fontStretch;
        public FontStretch FontStretch
        {
            get => _fontStretch;
            set => SetField(ref _fontStretch, value);
        }

        private Thickness _padding;
        public Thickness Padding
        {
            get => _padding;
            set => SetField(ref _padding, value);
        }

        private Thickness _margin;
        public Thickness Margin
        {
            get => _margin;
            set => SetField(ref _margin, value);
        }

        private HorizontalAlignment _horizontalAlignment;
        public HorizontalAlignment HorizontalAlignment
        {
            get => _horizontalAlignment;
            set => SetField(ref _horizontalAlignment, value);
        }

        private VerticalAlignment _verticalAlignment;
        public VerticalAlignment VerticalAlignment
        {
            get => _verticalAlignment;
            set => SetField(ref _verticalAlignment, value);
        }

        private HorizontalAlignment _horizontalContentAlignment;
        public HorizontalAlignment HorizontalContentAlignment
        {
            get => _horizontalContentAlignment;
            set => SetField(ref _horizontalContentAlignment, value);
        }

        private VerticalAlignment _verticalContentAlignment;
        public VerticalAlignment VerticalContentAlignment
        {
            get => _verticalContentAlignment;
            set => SetField(ref _verticalContentAlignment, value);
        }

        private double _width;
        public double Width
        {
            get => _width;
            set => SetField(ref _width, value);
        }

        private double _height;
        public double Height
        {
            get => _height;
            set => SetField(ref _height, value);
        }

        private double _minWidth;
        public double MinWidth
        {
            get => _minWidth;
            set => SetField(ref _minWidth, value);
        }

        private double _minHeight;
        public double MinHeight
        {
            get => _minHeight;
            set => SetField(ref _minHeight, value);
        }

        private double _maxWidth;
        public double MaxWidth
        {
            get => _maxWidth;
            set => SetField(ref _maxWidth, value);
        }

        private double _maxHeight;
        public double MaxHeight
        {
            get => _maxHeight;
            set => SetField(ref _maxHeight, value);
        }

        private Visibility _visibility;
        public Visibility Visibility
        {
            get => _visibility;
            set => SetField(ref _visibility, value);
        }

        private object _toolTip;
        public object ToolTip
        {
            get => _toolTip;
            set => SetField(ref _toolTip, value);
        }

        private Style _style;
        public Style Style
        {
            get => _style;
            set => SetField(ref _style, value);
        }

        private double _opacity;
        public double Opacity
        {
            get => _opacity;
            set => SetField(ref _opacity, value);
        }

        private bool _focusable;
        public bool Focusable
        {
            get => _focusable;
            set => SetField(ref _focusable, value);
        }

        private string _name;
        public string Name
        {
            get => _name;
            set => SetField(ref _name, value);
        }

        private object _tag;
        public object Tag
        {
            get => _tag;
            set => SetField(ref _tag, value);
        }

    }
}
