using BasicControls.Common;
using Feature.Infrastructure.Core;
using Feature.Infrastructure.Interfaces;
using System.Collections.ObjectModel;
using System.ComponentModel.Composition;

namespace BasicControls.PhaseTwo.Topics.AutoGeneratedTopics.RadioButton
{
    [Export(typeof(IIntroductionViewModel))]
    [ExportMetadata(MetaDataKeys.Title, AddonMetadataKeys.RadioButtonTitle)]
    internal class RadioButtonIntroductionViewModel : ControlIntroductionViewModel, IIntroductionViewModel
    {
        public override string Title => AddonMetadataKeys.RadioButtonTitle;

        public override string Header => "RadioButton Control";

        public override ObservableCollection<string> DescriptionCollection { get; } = new ObservableCollection<string>
        {
            "RadioButton controls are used in groups to allow only one selection at a time.",
"Each RadioButton in a group should have the same GroupName.",
"Useful for presenting mutually exclusive options."
        };

        public override string SamplesIntroductionHeader => "Few Samples of RadioButton are provided below";

        public RadioButtonSampleViewModel SampleContent {get;} = new RadioButtonSampleViewModel();
    }
}
