using System.Windows.Controls;

namespace PanelControls.Topics.AutoGeneratedTopics.Canvas
{
    /// <summary>
    /// Interaction logic for CanvasIntroductionView.xaml
    /// </summary>
    public partial class CanvasIntroductionView : UserControl
    {
        public CanvasIntroductionView()
        {
            InitializeComponent();
        }
    }
}
