using System.Windows.Controls;

namespace BasicControls.Topics.AutoGeneratedTopics.WrapPanel
{
    /// <summary>
    /// Interaction logic for WrapPanelIntroductionView.xaml
    /// </summary>
    public partial class WrapPanelIntroductionView : UserControl
    {
        public WrapPanelIntroductionView()
        {
            InitializeComponent();
        }
    }
}
