using System.Windows.Controls;

namespace BasicControls.PhaseTwo.Topics.AutoGeneratedTopics.Button
{
    /// <summary>
    /// Interaction logic for ButtonIntroductionView.xaml
    /// </summary>
    public partial class ButtonIntroductionView : UserControl
    {
        public ButtonIntroductionView()
        {
            InitializeComponent();
        }
    }
}
