using BasicControls.Common;
using Feature.Infrastructure.Core;
using Feature.Infrastructure.Interfaces;
using System.Collections.ObjectModel;
using System.ComponentModel.Composition;

namespace BasicControls.PhaseTwo.Topics.AutoGeneratedTopics.Button
{
    [Export(typeof(IIntroductionViewModel))]
    [ExportMetadata(MetaDataKeys.Title, AddonMetadataKeys.ButtonTitle)]
    internal class ButtonIntroductionViewModel : ControlIntroductionViewModel, IIntroductionViewModel
    {
        public override string Title => AddonMetadataKeys.ButtonTitle;

        public override string Header => "Button Control";

        public override ObservableCollection<string> DescriptionCollection { get; } = new ObservableCollection<string>
        {
            "The Button control is used to initiate an action when clicked.",
"It can contain text, images, or other UI elements as content.",
"Supports various properties for customization such as IsEnabled, Background, Foreground, etc."
        };

        public override string SamplesIntroductionHeader => "Few Samples of Button are provided below";

        public ButtonSampleViewModel SampleContent {get;} = new ButtonSampleViewModel();
    }
}
