using System.Windows.Controls;

namespace BasicControls.Topics.AutoGeneratedTopics.Grid
{
    /// <summary>
    /// Interaction logic for GridIntroductionView.xaml
    /// </summary>
    public partial class GridIntroductionView : UserControl
    {
        public GridIntroductionView()
        {
            InitializeComponent();
        }
    }
}
