using BasicControls.Common;
using Feature.Infrastructure.Core;
using Feature.Infrastructure.Interfaces;
using System.Collections.ObjectModel;
using System.ComponentModel.Composition;

namespace BasicControls.Topics.AutoGeneratedTopics.Grid
{
    [Export(typeof(IIntroductionViewModel))]
    [ExportMetadata(MetaDataKeys.Title, AddonMetadataKeys.GridTitle)]
    internal class GridIntroductionViewModel : ControlIntroductionViewModel, IIntroductionViewModel
    {
        public override string Title => AddonMetadataKeys.GridTitle;

        public override string Header => "Grid Panel";

        public override ObservableCollection<string> DescriptionCollection { get; } = new ObservableCollection<string>
        {
            "The Grid panel allows complex layouts using rows and columns.",
"Supports row and column spanning for flexible arrangements.",
"Ideal for forms, dashboards, and structured layouts."
        };

        public override string SamplesIntroductionHeader => "Few Samples of Grid are provided below";
    }
}
