using BasicControls.Common;
using Feature.Infrastructure.Core;
using Feature.Infrastructure.Interfaces;
using System.Collections.ObjectModel;
using System.ComponentModel.Composition;

namespace PanelControls.Topics.AutoGeneratedTopics.WrapPanel
{
    [Export(typeof(IIntroductionViewModel))]
    [ExportMetadata(MetaDataKeys.Title, AddonMetadataKeys.WrapPanelTitle)]
    internal class WrapPanelIntroductionViewModel : ControlIntroductionViewModel, IIntroductionViewModel
    {
        public override string Title => AddonMetadataKeys.WrapPanelTitle;

        public override string Header => "WrapPanel";

        public override ObservableCollection<string> DescriptionCollection { get; } = new ObservableCollection<string>
        {
            "The WrapPanel arranges child elements in a horizontal or vertical orientation.",
"When there is not enough space, elements wrap to the next line or column.",
"Useful for toolbars, galleries, or dynamic layouts."
        };

        public override string SamplesIntroductionHeader => "Few Samples of WrapPanel are provided below";
    }
}
