// Auto-generated file, DO NOT MODIFY
using Feature.Infrastructure.Core;
using Feature.Infrastructure.Interfaces;
using System.ComponentModel.Composition;

namespace PanelControls.Topics.AutoGeneratedTopics
{
    [Export(typeof(IFeatureDemoSubTopic))]
    [ExportMetadata(MetaDataKeys.TopicName, AddonMetadataKeys.PanelsTitle)]
    public partial class WrapPanelSubTopic : IFeatureDemoSubTopic
    {
        public string Title => AddonMetadataKeys.WrapPanelTitle;
    }
}
